### ISSUE TITLE
Please describe general usage (english) - I'm happy to translate afterwards

### ISSUE THREAD

**Issue by rolandkohn** [shkdee/KeePassPHP-UI#1]
I'm not too familiar with french - but I guess I can do the translation then with technical understanding and online translators...

**Comment by marclaporte** [comment]
Hi!

If you extract all the French strings to a list, I can translate to English. Will you then be able to incorporate to the code and set us up so other languages can be added?

Thanks!

**Comment by shkdee** [comment]
Thank you very much for your kind offer.

Sooo I don't know if you already took a look at the code of the UI but it's actually a huge mess (I never tried to do it as clean as the main KeePassPHP project), and as a matter of fact i can NOT extract all French strings into a list right now because of that. But I will try to re-organize everything to abstract the language, that is definitely needed.

**Comment by shkdee** [comment]
I added an (probably bad) English translation my last commit (c18372748f0244a6455d1c889aef5b4dab1a0542). Don't hesitate to improve it!

**Comment by marclaporte** [comment]
Done ;-)
