### ISSUE TITLE
Improve ajax timeout behavior

### ISSUE THREAD

**Issue by mendel129** [shkdee/KeePassPHP-UI#5]
Hello,

Seems like a great app, but I'm currently having some "timeout"-issues...
My DB does open in the php ui, and all "readable" (title & username) data is visible.
But hitting a "Show" button will result in a "timeout" error message...

The DB itself is 2MB (changed the MAX_FILE_SIZE value), and it does open as you would expect...

Any ideas?

Thanks!

**Comment by shkdee** [comment]
My best guess for now is that the database takes too much time to open on your server, and that either PHP at server side (depending on its configuration, I think the default max execution time for a script is 30s), or javascript at client side (ajax timeout time is hard-set to 20s currently), decides that it's too long.

Did you change the value of the number of encryptions of the master key in your database ? The default value is 6000, which PHP should handle fast enough based on my experience, but if you changed it, it may be too hard for PHP. If you did, try lowering it to see if it gets better. If it's still 6000 (or if you don't want to change it), you can try to change the ajax timeout time in js/main.js (line 201) to wait longer.

If none of those work, I'll try to dig deeper.

**Comment by mendel129** [comment]
Thanks for your answer!

I'll change the execution time and let you know.

I did, for sure, change the encryption rounds. So yes, that can actually be the cause... But then it seems weird to me that the rest of the data is readable, only the passwords aren't? Or are they split up in the db itself?

**Comment by shkdee** [comment]
Nope, they are not split up, so it would seem slightly weird to me as well. But the rest of the data is extracted from the database when it is uploaded, which does not occur through an ajax query, so in that case the only possible timeout would be due to PHP, or something else in the server. Whereas when you load a password, your client only waits for 20s.

Now, I did set the limit of 20s without much thinking about it, it may not be suitable for all cases. Maybe I should make it more flexible, or more customizable...

**Comment by mendel129** [comment]
Yes, increasing the timeout values does indeed return the passwords! Perfect. Thanks!

They do come back really tiny in the interface, is that correct? Is it meant to be copy-pasted to become readable?

**Comment by shkdee** [comment]
Yeah, that's the indented behaviour. I have guessed you would usually rather copy-paste them into a password field than try to read them...
